{"id":"../../utils/catchAsyncErrors.js","dependencies":[{"name":"C:\\Users\\user\\Downloads\\Backend\\udemy\\Natours\\package.json","includedInParent":true,"mtime":1687596866648}],"generated":{"js":"module.exports = function (fn) {\n  // returning another anonymous function which will also return a resolved or rejected promise\n  return function (req, res, next) {\n    // calling the asyncronous function and it will return a promise\n    fn(req, res, next).catch(function (err) {\n      return next(err);\n    });\n    // the Error thrown by the request handlers is not an instance of the appError class we created, so it does not have the property isoperational in it.\n  };\n};"},"sourceMaps":{"js":{"mappings":[{"generated":{"line":1,"column":0},"source":"../../utils/catchAsyncErrors.js","original":{"line":1,"column":0},"name":"module"},{"generated":{"line":1,"column":6},"source":"../../utils/catchAsyncErrors.js","original":{"line":1,"column":6}},{"generated":{"line":1,"column":7},"source":"../../utils/catchAsyncErrors.js","original":{"line":1,"column":7},"name":"exports"},{"generated":{"line":1,"column":14},"source":"../../utils/catchAsyncErrors.js","original":{"line":1,"column":14}},{"generated":{"line":1,"column":17},"source":"../../utils/catchAsyncErrors.js","original":{"line":1,"column":17}},{"generated":{"line":1,"column":27},"source":"../../utils/catchAsyncErrors.js","original":{"line":1,"column":17},"name":"fn"},{"generated":{"line":1,"column":29},"source":"../../utils/catchAsyncErrors.js","original":{"line":1,"column":19}},{"generated":{"line":1,"column":31},"source":"../../utils/catchAsyncErrors.js","original":{"line":1,"column":23}},{"generated":{"line":2,"column":2},"source":"../../utils/catchAsyncErrors.js","original":{"line":2,"column":4}},{"generated":{"line":3,"column":2},"source":"../../utils/catchAsyncErrors.js","original":{"line":3,"column":4}},{"generated":{"line":3,"column":9},"source":"../../utils/catchAsyncErrors.js","original":{"line":3,"column":11}},{"generated":{"line":3,"column":19},"source":"../../utils/catchAsyncErrors.js","original":{"line":3,"column":12},"name":"req"},{"generated":{"line":3,"column":22},"source":"../../utils/catchAsyncErrors.js","original":{"line":3,"column":15}},{"generated":{"line":3,"column":24},"source":"../../utils/catchAsyncErrors.js","original":{"line":3,"column":17},"name":"res"},{"generated":{"line":3,"column":27},"source":"../../utils/catchAsyncErrors.js","original":{"line":3,"column":20}},{"generated":{"line":3,"column":29},"source":"../../utils/catchAsyncErrors.js","original":{"line":3,"column":22},"name":"next"},{"generated":{"line":3,"column":33},"source":"../../utils/catchAsyncErrors.js","original":{"line":3,"column":26}},{"generated":{"line":3,"column":35},"source":"../../utils/catchAsyncErrors.js","original":{"line":3,"column":31}},{"generated":{"line":4,"column":4},"source":"../../utils/catchAsyncErrors.js","original":{"line":4,"column":8}},{"generated":{"line":5,"column":4},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":8},"name":"fn"},{"generated":{"line":5,"column":6},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":10}},{"generated":{"line":5,"column":7},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":11},"name":"req"},{"generated":{"line":5,"column":10},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":14}},{"generated":{"line":5,"column":12},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":15},"name":"res"},{"generated":{"line":5,"column":15},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":18}},{"generated":{"line":5,"column":17},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":19},"name":"next"},{"generated":{"line":5,"column":21},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":23}},{"generated":{"line":5,"column":22},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":24}},{"generated":{"line":5,"column":23},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":25},"name":"catch"},{"generated":{"line":5,"column":28},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":30}},{"generated":{"line":5,"column":29},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":31}},{"generated":{"line":5,"column":39},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":31},"name":"err"},{"generated":{"line":5,"column":42},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":34}},{"generated":{"line":6,"column":6},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":34}},{"generated":{"line":6,"column":13},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":38},"name":"next"},{"generated":{"line":6,"column":17},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":42}},{"generated":{"line":6,"column":18},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":43},"name":"err"},{"generated":{"line":6,"column":21},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":46}},{"generated":{"line":6,"column":22},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":47}},{"generated":{"line":7,"column":4},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":47}},{"generated":{"line":7,"column":6},"source":"../../utils/catchAsyncErrors.js","original":{"line":5,"column":48}},{"generated":{"line":8,"column":4},"source":"../../utils/catchAsyncErrors.js","original":{"line":6,"column":8}},{"generated":{"line":9,"column":2},"source":"../../utils/catchAsyncErrors.js","original":{"line":7,"column":4}},{"generated":{"line":9,"column":3},"source":"../../utils/catchAsyncErrors.js","original":{"line":7,"column":5}},{"generated":{"line":10,"column":0},"source":"../../utils/catchAsyncErrors.js","original":{"line":8,"column":0}},{"generated":{"line":10,"column":1},"source":"../../utils/catchAsyncErrors.js","original":{"line":8,"column":1}}],"sources":{"../../utils/catchAsyncErrors.js":"module.exports = fn => {\r\n    // returning another anonymous function which will also return a resolved or rejected promise\r\n    return (req, res, next) => {\r\n        // calling the asyncronous function and it will return a promise\r\n        fn(req,res,next).catch(err => next(err)) \r\n        // the Error thrown by the request handlers is not an instance of the appError class we created, so it does not have the property isoperational in it.\r\n    }\r\n}"},"lineCount":null}},"error":null,"hash":"b1321b98c1c34ace0c20102499a1a31c","cacheData":{"env":{}}}